name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          apt install -y doxygen
          pip3 install -U sphinx breathe sphinx-rtd-theme recommonmark
      - name: build docs
        run: |
          cd docs
          make html
          cd ..
      - name: deploy docs
        run: |
          bash scripts/deploy_docs.sh
