name: Documentation

on:
  push:
    branches:
      - master
      - test-deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install dependencies
        run: |
          sudo apt-get install -y doxygen
          pip install -U sphinx breathe sphinx-rtd-theme recommonmark
      - name: build docs
        run: |
          export PATH="/home/runner/.local/bin:$PATH"
          cd docs
          make html
          cd ..
      - name: deploy docs
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          bash scripts/deploy_docs.sh
